// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.RAAG.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializerejectJoinPayload")
public inline fun rejectJoinPayload(block: com.RAAG.music.listentogether.proto.RejectJoinPayloadKt.Dsl.() -> kotlin.Unit): com.RAAG.music.listentogether.proto.Listentogether.RejectJoinPayload =
  com.RAAG.music.listentogether.proto.RejectJoinPayloadKt.Dsl._create(com.RAAG.music.listentogether.proto.Listentogether.RejectJoinPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.RAAG.music.listentogether.proto.RejectJoinPayload`
 */
public object RejectJoinPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.RAAG.music.listentogether.proto.Listentogether.RejectJoinPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.RAAG.music.listentogether.proto.Listentogether.RejectJoinPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.RAAG.music.listentogether.proto.Listentogether.RejectJoinPayload = _builder.build()

    /**
     * `string userId = 1;`
     */
    public var userId: kotlin.String
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `string userId = 1;`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * `string reason = 2;`
     */
    public var reason: kotlin.String
      @kotlin.jvm.JvmName("getReason")
        get() = _builder.reason
      @kotlin.jvm.JvmName("setReason")
        set(value) {
        _builder.reason = value
      }
    /**
     * `string reason = 2;`
     */
    public fun clearReason() {
      _builder.clearReason()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.RAAG.music.listentogether.proto.Listentogether.RejectJoinPayload.copy(block: `com.RAAG.music.listentogether.proto`.RejectJoinPayloadKt.Dsl.() -> kotlin.Unit): com.RAAG.music.listentogether.proto.Listentogether.RejectJoinPayload =
  `com.RAAG.music.listentogether.proto`.RejectJoinPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

