// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.RAAG.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializeroomCreatedPayload")
public inline fun roomCreatedPayload(block: com.RAAG.music.listentogether.proto.RoomCreatedPayloadKt.Dsl.() -> kotlin.Unit): com.RAAG.music.listentogether.proto.Listentogether.RoomCreatedPayload =
  com.RAAG.music.listentogether.proto.RoomCreatedPayloadKt.Dsl._create(com.RAAG.music.listentogether.proto.Listentogether.RoomCreatedPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.RAAG.music.listentogether.proto.RoomCreatedPayload`
 */
public object RoomCreatedPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.RAAG.music.listentogether.proto.Listentogether.RoomCreatedPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.RAAG.music.listentogether.proto.Listentogether.RoomCreatedPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.RAAG.music.listentogether.proto.Listentogether.RoomCreatedPayload = _builder.build()

    /**
     * `string roomCode = 1;`
     */
    public var roomCode: kotlin.String
      @kotlin.jvm.JvmName("getRoomCode")
        get() = _builder.roomCode
      @kotlin.jvm.JvmName("setRoomCode")
        set(value) {
        _builder.roomCode = value
      }
    /**
     * `string roomCode = 1;`
     */
    public fun clearRoomCode() {
      _builder.clearRoomCode()
    }

    /**
     * `string userId = 2;`
     */
    public var userId: kotlin.String
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `string userId = 2;`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * `string sessionToken = 3;`
     */
    public var sessionToken: kotlin.String
      @kotlin.jvm.JvmName("getSessionToken")
        get() = _builder.sessionToken
      @kotlin.jvm.JvmName("setSessionToken")
        set(value) {
        _builder.sessionToken = value
      }
    /**
     * `string sessionToken = 3;`
     */
    public fun clearSessionToken() {
      _builder.clearSessionToken()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.RAAG.music.listentogether.proto.Listentogether.RoomCreatedPayload.copy(block: `com.RAAG.music.listentogether.proto`.RoomCreatedPayloadKt.Dsl.() -> kotlin.Unit): com.RAAG.music.listentogether.proto.Listentogether.RoomCreatedPayload =
  `com.RAAG.music.listentogether.proto`.RoomCreatedPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

