// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: listentogether.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.RAGG.music.listentogether.proto;

@kotlin.jvm.JvmName("-initializesuggestionReceivedPayload")
public inline fun suggestionReceivedPayload(block: com.RAGG.music.listentogether.proto.SuggestionReceivedPayloadKt.Dsl.() -> kotlin.Unit): com.RAGG.music.listentogether.proto.Listentogether.SuggestionReceivedPayload =
  com.RAGG.music.listentogether.proto.SuggestionReceivedPayloadKt.Dsl._create(com.RAGG.music.listentogether.proto.Listentogether.SuggestionReceivedPayload.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `com.RAGG.music.listentogether.proto.SuggestionReceivedPayload`
 */
public object SuggestionReceivedPayloadKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.RAGG.music.listentogether.proto.Listentogether.SuggestionReceivedPayload.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.RAGG.music.listentogether.proto.Listentogether.SuggestionReceivedPayload.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.RAGG.music.listentogether.proto.Listentogether.SuggestionReceivedPayload = _builder.build()

    /**
     * `string suggestionId = 1;`
     */
    public var suggestionId: kotlin.String
      @kotlin.jvm.JvmName("getSuggestionId")
        get() = _builder.suggestionId
      @kotlin.jvm.JvmName("setSuggestionId")
        set(value) {
        _builder.suggestionId = value
      }
    /**
     * `string suggestionId = 1;`
     */
    public fun clearSuggestionId() {
      _builder.clearSuggestionId()
    }

    /**
     * `string fromUserId = 2;`
     */
    public var fromUserId: kotlin.String
      @kotlin.jvm.JvmName("getFromUserId")
        get() = _builder.fromUserId
      @kotlin.jvm.JvmName("setFromUserId")
        set(value) {
        _builder.fromUserId = value
      }
    /**
     * `string fromUserId = 2;`
     */
    public fun clearFromUserId() {
      _builder.clearFromUserId()
    }

    /**
     * `string fromUsername = 3;`
     */
    public var fromUsername: kotlin.String
      @kotlin.jvm.JvmName("getFromUsername")
        get() = _builder.fromUsername
      @kotlin.jvm.JvmName("setFromUsername")
        set(value) {
        _builder.fromUsername = value
      }
    /**
     * `string fromUsername = 3;`
     */
    public fun clearFromUsername() {
      _builder.clearFromUsername()
    }

    /**
     * `.com.RAGG.music.listentogether.proto.TrackInfo trackInfo = 4;`
     */
    public var trackInfo: com.RAGG.music.listentogether.proto.Listentogether.TrackInfo
      @kotlin.jvm.JvmName("getTrackInfo")
        get() = _builder.trackInfo
      @kotlin.jvm.JvmName("setTrackInfo")
        set(value) {
        _builder.trackInfo = value
      }
    /**
     * `.com.RAGG.music.listentogether.proto.TrackInfo trackInfo = 4;`
     */
    public fun clearTrackInfo() {
      _builder.clearTrackInfo()
    }
    /**
     * `.com.RAGG.music.listentogether.proto.TrackInfo trackInfo = 4;`
     * @return Whether the trackInfo field is set.
     */
    public fun hasTrackInfo(): kotlin.Boolean {
      return _builder.hasTrackInfo()
    }

    public val SuggestionReceivedPayloadKt.Dsl.trackInfoOrNull: com.RAGG.music.listentogether.proto.Listentogether.TrackInfo?
      get() = _builder.trackInfoOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.RAGG.music.listentogether.proto.Listentogether.SuggestionReceivedPayload.copy(block: `com.RAGG.music.listentogether.proto`.SuggestionReceivedPayloadKt.Dsl.() -> kotlin.Unit): com.RAGG.music.listentogether.proto.Listentogether.SuggestionReceivedPayload =
  `com.RAGG.music.listentogether.proto`.SuggestionReceivedPayloadKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.RAGG.music.listentogether.proto.Listentogether.SuggestionReceivedPayloadOrBuilder.trackInfoOrNull: com.RAGG.music.listentogether.proto.Listentogether.TrackInfo?
  get() = if (hasTrackInfo()) getTrackInfo() else null

